### ISSUE TITLE
Implementing setState

### ISSUE THREAD

**Issue by tbranyen** [apaleslimghost/excise#1]
Have you considered adding in `setState`-like functionality?

Maybe something like this:

``` js
import { outerHTML } from 'diffhtml';

class StatefulComponent extends Component {
  setState(newState) {
    this.state = Object.assign({}, this.state, newState);

    // Patch the previously rendered node with the new VTree.
    outerHTML(this, this.render());
  }
}
```

**Comment by apaleslimghost** [comment]
I played around with it at first. For me, [`StatefulComponent`](https://github.com/quarterto/excise/blob/master/stateful.js) and `setAttribute` are enough, and I'd suggest some external state container for anything more hardcore.
